"""
GUARDIAN OS
AI Intelligence Models

Purpose:
    Define the structured contract between Guardian's
    deterministic operational engines and its AI layer.

The AI layer receives structured operational facts and
produces explanations, recommendations, and summaries.

Important:
    The AI layer does NOT calculate operational risk.
    The deterministic engines remain the source of truth.
"""


from dataclasses import dataclass, field
from typing import Dict, List, Optional


# ============================================================
# RISK DRIVER
# ============================================================

@dataclass(frozen=True)
class RiskDriver:
    """
    A structured explanation of one factor contributing
    to operational risk.
    """

    name: str

    value: float

    contribution: float

    description: str


# ============================================================
# SCENARIO SUMMARY
# ============================================================

@dataclass(frozen=True)
class ScenarioSummary:
    """
    Structured representation of one simulated intervention.
    """

    strategy: str

    projected_risk: float

    projected_utilization: float

    projected_capacity: float

    projected_load: float

    projected_routes: int

    risk_reduction: float

    utilization_improvement: float

    decision_score: float

    safety_passed: bool


# ============================================================
# OPERATIONAL CONTEXT
# ============================================================

@dataclass(frozen=True)
class OperationalContext:
    """
    Complete structured context supplied to the AI layer.

    This object combines deterministic outputs from:

        Event Ingestion
        Risk Engine
        Simulation Engine
        Intervention Engine
        Execution Engine
        Outcome Engine
    """

    station_id: str

    city: str

    region: str

    event_type: str

    event_severity: str

    event_description: str

    capacity: float

    current_load: float

    active_routes: int

    utilization: float

    risk_score: float

    risk_level: str

    risk_drivers: List[RiskDriver] = field(
        default_factory=list
    )

    scenarios: List[ScenarioSummary] = field(
        default_factory=list
    )

    selected_strategy: Optional[str] = None

    decision_score: Optional[float] = None

    execution_status: Optional[str] = None

    outcome_status: Optional[str] = None

    outcome_effectiveness: Optional[float] = None

    metadata: Dict = field(
        default_factory=dict
    )


# ============================================================
# AI EXPLANATION
# ============================================================

@dataclass(frozen=True)
class AIExplanation:
    """
    Natural-language explanation generated by the AI layer.

    The values remain traceable to deterministic inputs.
    """

    summary: str

    key_risks: List[str]

    operational_implications: List[str]

    confidence_note: str


# ============================================================
# AI RECOMMENDATION
# ============================================================

@dataclass(frozen=True)
class AIRecommendation:
    """
    AI-generated operational recommendation.

    The AI does not directly execute the recommendation.
    """

    recommended_action: str

    reasoning: str

    expected_effect: str

    constraints: List[str]

    requires_human_review: bool


# ============================================================
# AI INTELLIGENCE RESULT
# ============================================================

@dataclass(frozen=True)
class IntelligenceResult:
    """
    Complete output of Guardian's AI Intelligence Layer.
    """

    station_id: str

    explanation: AIExplanation

    recommendation: AIRecommendation

    generated_by: str

    model_id: Optional[str] = None

    grounded_in_deterministic_data: bool = True

    metadata: Dict = field(
        default_factory=dict
    )


# ============================================================
# CONTEXT SERIALIZATION
# ============================================================

def context_to_dict(
    context: OperationalContext,
) -> Dict:
    """
    Convert OperationalContext into a JSON-compatible
    dictionary.

    This will later become the payload passed into the
    Bedrock orchestration layer.
    """

    return {
        "station_id": context.station_id,

        "city": context.city,

        "region": context.region,

        "event": {
            "type": context.event_type,

            "severity": context.event_severity,

            "description": context.event_description,
        },

        "station_state": {
            "capacity": context.capacity,

            "current_load": context.current_load,

            "active_routes": context.active_routes,

            "utilization": context.utilization,
        },

        "risk": {
            "score": context.risk_score,

            "level": context.risk_level,

            "drivers": [
                {
                    "name": driver.name,

                    "value": driver.value,

                    "contribution": driver.contribution,

                    "description": driver.description,
                }

                for driver in context.risk_drivers
            ],
        },

        "scenarios": [
            {
                "strategy": scenario.strategy,

                "projected_risk": (
                    scenario.projected_risk
                ),

                "projected_utilization": (
                    scenario.projected_utilization
                ),

                "projected_capacity": (
                    scenario.projected_capacity
                ),

                "projected_load": (
                    scenario.projected_load
                ),

                "projected_routes": (
                    scenario.projected_routes
                ),

                "risk_reduction": (
                    scenario.risk_reduction
                ),

                "utilization_improvement": (
                    scenario.utilization_improvement
                ),

                "decision_score": (
                    scenario.decision_score
                ),

                "safety_passed": (
                    scenario.safety_passed
                ),
            }

            for scenario in context.scenarios
        ],

        "decision": {
            "selected_strategy": (
                context.selected_strategy
            ),

            "decision_score": (
                context.decision_score
            ),
        },

        "execution": {
            "status": context.execution_status,
        },

        "outcome": {
            "status": context.outcome_status,

            "effectiveness": (
                context.outcome_effectiveness
            ),
        },

        "metadata": context.metadata,
    }


# ============================================================
# LOCAL CONTRACT TEST
# ============================================================

if __name__ == "__main__":

    print("=" * 70)
    print("GUARDIAN OS — AI INTELLIGENCE MODELS TEST")
    print("=" * 70)

    # --------------------------------------------------------
    # Example risk drivers
    # --------------------------------------------------------

    risk_drivers = [
        RiskDriver(
            name="Station Utilization",

            value=102.50,

            contribution=40.00,

            description=(
                "Station utilization exceeds available capacity."
            ),
        ),

        RiskDriver(
            name="Capacity Overload",

            value=2.50,

            contribution=6.25,

            description=(
                "Current load exceeds station capacity."
            ),
        ),
    ]

    # --------------------------------------------------------
    # Example scenarios
    # --------------------------------------------------------

    scenarios = [
        ScenarioSummary(
            strategy="HYBRID_RESPONSE",

            projected_risk=39.26,

            projected_utilization=83.86,

            projected_capacity=8800.0,

            projected_load=7380.0,

            projected_routes=346,

            risk_reduction=46.05,

            utilization_improvement=18.64,

            decision_score=46.56,

            safety_passed=True,
        ),

        ScenarioSummary(
            strategy="ROUTE_REBALANCE",

            projected_risk=44.44,

            projected_utilization=87.12,

            projected_capacity=8000.0,

            projected_load=6970.0,

            projected_routes=326,

            risk_reduction=38.93,

            utilization_improvement=15.38,

            decision_score=39.56,

            safety_passed=True,
        ),

        ScenarioSummary(
            strategy="CAPACITY_SHIFT",

            projected_risk=50.43,

            projected_utilization=89.13,

            projected_capacity=9200.0,

            projected_load=8200.0,

            projected_routes=384,

            risk_reduction=30.70,

            utilization_improvement=13.37,

            decision_score=32.57,

            safety_passed=True,
        ),
    ]

    # --------------------------------------------------------
    # Build operational context
    # --------------------------------------------------------

    context = OperationalContext(

        station_id="CHN-017",

        city="Chennai",

        region="Tamil Nadu",

        event_type="STATION_CAPACITY_SHOCK",

        event_severity="HIGH",

        event_description=(
            "Synthetic station capacity disruption"
        ),

        capacity=8000,

        current_load=8200,

        active_routes=384,

        utilization=102.50,

        risk_score=72.77,

        risk_level="HIGH",

        risk_drivers=risk_drivers,

        scenarios=scenarios,

        selected_strategy="HYBRID_RESPONSE",

        decision_score=46.56,

        execution_status="EXECUTED",

        outcome_status="IMPROVED",

        outcome_effectiveness=51.52,

        metadata={
            "simulation": True,

            "data_source": "synthetic",
        },
    )

    # --------------------------------------------------------
    # Serialize
    # --------------------------------------------------------

    serialized = context_to_dict(
        context
    )

    print("\nCONTEXT CREATED")
    print("-" * 70)

    print(
        f"Station: "
        f"{context.station_id}"
    )

    print(
        f"Event: "
        f"{context.event_type}"
    )

    print(
        f"Risk: "
        f"{context.risk_score:.2f}/100"
    )

    print(
        f"Risk Level: "
        f"{context.risk_level}"
    )

    print(
        f"Scenarios: "
        f"{len(context.scenarios)}"
    )

    print(
        f"Selected Strategy: "
        f"{context.selected_strategy}"
    )

    print(
        f"Execution: "
        f"{context.execution_status}"
    )

    print(
        f"Outcome: "
        f"{context.outcome_status}"
    )

    print("\nSERIALIZATION")
    print("-" * 70)

    print(
        f"Top-level fields: "
        f"{len(serialized)}"
    )

    print(
        f"Risk drivers serialized: "
        f"{len(serialized['risk']['drivers'])}"
    )

    print(
        f"Scenarios serialized: "
        f"{len(serialized['scenarios'])}"
    )

    print(
        "\nAI contract ready."
    )

    print("\n" + "=" * 70)
    print("AI INTELLIGENCE MODELS TEST COMPLETE")
    print("=" * 70)